### ISSUE TITLE
Unread Messages Feedback

### ISSUE THREAD

**Issue by dseehof** [bitfocus/companion-module-microsoft-teams#5]
Looks like the "unread messages" feedback is not working, every other feedback does. Any way for me to provide more info for troubleshooting?

**Comment by Jarec-au** [comment]
This appears to be a bug in Microsoft Teams.
I tested this morning with unread messages from general chats, unread messages from groups as well as an unread message in the active meeting. It doesn't seem to matter where I have unread messages, Teams doesn't send the state 'true'.

Message received from Teams as below.

debug: Message Received: 
"meetingState":{
  "isMuted":true,
  "isVideoOn":false,
  "isHandRaised":false,
  "isInMeeting":true,
  "isRecordingOn":false,
  "isBackgroundBlurred":false,
  "isSharing":false,
  "hasUnreadMessages":false
}

**Comment by dseehof** [comment]
Did anyone get lucky with some of the updates MS rolled out - still not working for me, just curious.

**Comment by Jarec-au** [comment]
I had a look again tonight. Nope, doesn't seem to be set by anything.
