### ISSUE TITLE
Any chance for an "is muted" boolean variable?

### ISSUE THREAD

**Issue by patrichard** [bitfocus/companion-module-microsoft-teams#6]
I'd like to make use of the generic-blink module, which can check a variable and then blink a button if it evaluates true. Any chance we could get a button to show that it's muted?

**Comment by Jarec-au** [comment]
Yes, that's already built in.
Look under feedbacks, there's an 'is muted' condition.
If you add the pre-made microphone button, you can see how it is used.

**Comment by patrichard** [comment]
How do you specify that as an internal variable, like $(internal:connection_Teams_status)?. You need a variable to check against when using generic-blink.
![image](https://github.com/bitfocus/companion-module-microsoft-teams/assets/8019188/a0bad677-79a6-496c-97ae-22e9aaa582b4)

**Comment by Jarec-au** [comment]
Sorry, I see what you mean now.
I'll see what I can do

**Comment by Jarec-au** [comment]
Code added to 1.2.1 to support frontend variables function.

**Comment by patrichard** [comment]
Anything to show current mute status?

**Comment by Jarec-au** [comment]
Yep, that'll be in there, it's just that the screenshot from before was only as big as the window that I currently had open, just scrolled down a bit:
![{A87D29AB-D030-4B50-AE60-86D0BECD34D1}](https://github.com/user-attachments/assets/1b3af686-861c-46e2-bdf8-ede507fb4e82)

**Comment by patrichard** [comment]
Awesome. Thanks for all your hard work.

**Comment by joezimjs** [comment]
Will this get into Companion 3.5?
