### ISSUE TITLE
Please Add Variables

### ISSUE THREAD

**Issue by joezimjs** [bitfocus/companion-module-microsoft-teams#9]
It's wonderful that you have all the Feedback options, but I'd like to use Triggers to run actions based on state change (e.g. turn a key light on/off when I enter/leave a meeting), so I need much of the state to be visible via Variables, so I can trigger actions based on them changing.

Specifically I need to know whether or not I'm in a meeting, but I'm sure others could benefit from other variables such as #6.

**Comment by patrichard** [comment]
Triggers can watch a variable as the event. So I tried using Teams:isInMeeting, with no condition and an action set to toggle a fan in my office. I joined a meeting, and the variable did change, and Companion triggered the fan. 

![image](https://github.com/user-attachments/assets/5e98f15a-9670-4522-ab11-b396a5d60187)

**Comment by joezimjs** [comment]
Exactly, but I don't see any variables:

![image](https://github.com/user-attachments/assets/d8c0666e-8c31-4425-b178-016515fd19ee)

![image](https://github.com/user-attachments/assets/a640a0f8-230f-438d-b2f1-be72043f781c)

That's why I was asking you to add variables

**Comment by joezimjs** [comment]
OK, I just read the rest of #6. I see you added them in 1.2.1, but they're not showing up for me in Companion 3.4.1, which is using 1.2.0 of this module.
